FROM scratch
ARG REVISION
LABEL org.opencontainers.image.source="https://github.com/oso7865-ship-it/Prism-Frontend"
LABEL org.opencontainers.image.revision="${REVISION}"
COPY . /site/
CMD ["/static-artifact-not-executable"]
